# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
#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

- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://MattTrinder1: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@github.com/MattTrinder1/PfP2'
