# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
#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

- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://MattTrinder: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@github.com/MattTrinder1/PfP2'
