trigger: none
  #batch: true
  #branches: 
  #    include:
  #    - master
  #paths:
  #  include:
  #  - Schema/*
  #  - Plugins/*
  #  - Tests/*
  #  - DataMigration/*

#schedules:
#- cron: "05 12 * * 1-5"
#  displayName: Daily Lunchtime Release
#  branches:
#    include:
#    - master

#- cron: "05 17 * * 1-5"
#  displayName: Daily Evening Release
#  branches:
#    include:
#    - master

name: $(BuildID)

pool:
  vmImage: 'windows-2019'
  #name: MOD Pool
  #demands: agent.name -equals ModTestHost2


variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: PP

#pre-test
- name: pretest.username
  value: matt.trinder@tisski.com
- name: pretest.password
  value: hsgwrmhbrcltjxlw 
- name: pretest.instancename
  value: cumbriapretest
- name: pretest.url
  value: https://$(pretest.instancename).crm11.dynamics.com
- name: pretest.connection.string
  value: RequireNewInstance=True;AuthType=Office365;Username=$(pretest.username);Password=$(pretest.password);Url=$(pretest.url)

#cumbria-creds
- name: cumbria.username
  value: powerapps.service@cumbria.police.uk
- name: cumbria.password
  value: Shut.shower.dine1 

#install-test
#- name: installtest.instancename
#  value: cumbria-build
#- name: installtest.url
#  value: https://$(installtest.instancename).crm11.dynamics.com
#- name: installtest.connection.string
#  value: RequireNewInstance=True;AuthType=Office365;Username=$(cumbria.username);Password=$(cumbria.password);Url=$(installtest.url)

#install-test
#- name: prerelease.instancename
#  value: cumbria-prerelease
#- name: prerelease.url
#  value: https://$(prerelease.instancename).crm11.dynamics.com
#- name: prerelease.connection.string
#  value: RequireNewInstance=True;AuthType=Office365;Username=$(cumbria.username);Password=$(cumbria.password);Url=$(prerelease.url)

#uat
- name: uat.instancename
  value: cumbria-build
- name: uat.url
  value: https://$(uat.instancename).crm11.dynamics.com
- name: uat.connection.string
  value: RequireNewInstance=True;AuthType=Office365;Username=$(cumbria.username);Password=$(cumbria.password);Url=$(uat.url)

#live
- name: prod.instancename
  value: cops
- name: prod.url
  value: https://$(prod.instancename).crm11.dynamics.com
- name: prod.connection.string
  value: RequireNewInstance=True;AuthType=Office365;Username=$(cumbria.username);Password=$(cumbria.password);Url=$(prod.url)

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - template: assembleRelease.yml
        parameters:
          managed: Managed
          minorversion : $(minor.version)
          releaseversion : $(release.version)
          solutionprefix : $(solution.prefix)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------

