parameters:
- name: solutionName
  type: string
- name: solutionprefix
  type: string
- name: minorversion
  type: string
- name: releaseversion
  type: string
- name: connectionString
  type: string

steps:
    
- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'   

- task: MSCRMGetConfigurationRecord@12
  inputs:
    crmConnectionString: $(pfpsystemtest.connection.string)
    entityName: 'cp_configdatahistory'
    lookupFieldName: 'cp_name'
    valueFieldName: 'cp_value'
    lookupValue: 'CurrentVersionRPRP'
    existsVariableName: 'configExists'
    valueVariableName: 'currentConfigVersion'

- powershell: |
        $value = Get-Content  -Path $(Build.SourcesDirectory)/ConfigData/CumbriaRPRPVersionDate.txt 
        Write-Host "##vso[task.setvariable variable=newConfigVersion]$value"

- task: MSCRMImportCMData@12
  displayName: Import Configuration Data
  inputs:
    crmConnectionString: $(pfpsystemtest.connection.string)
    dataFile: $(Build.SourcesDirectory)/ConfigData/CumbriaRPRP.zip
  condition: ne (variables.newConfigVersion,variables.currentConfigVersion)


- task: MSCRMUpdateConfigurationRecords@12
  inputs:
    crmConnectionString: '$(pfpsystemtest.connection.string)'
    entityName: 'cp_configdatahistory'
    lookupFieldName: 'cp_name'
    valueFieldName: 'cp_value'
    configurationRecordsJson: '[[''CurrentVersionRPRP'',''$(newConfigVersion)'']]'
  condition: ne (variables.newConfigVersion,variables.currentConfigVersion)
