parameters:
- name: solutionName
  type: string
- name: solutionprefix
  type: string
- name: minorversion
  type: string
- name: releaseversion
  type: string
- name: connectionString
  type: string

steps:
    
- template: get-solution-filenames.yml
  parameters:
    pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
    minorversion : ${{parameters.minorversion}}
    releaseversion : ${{parameters.releaseversion}}
    solutionprefix : ${{parameters.solutionprefix}}

- template: install-managed-solution.yml
  parameters:
    pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
    connectionstring : ${{parameters.connectionString}}
    SolutionFileName : $(${{parameters.solutionName}}SolutionFileName)