trigger: 
- none



pool:
  name: MOD Pool

variables:
- template: connectionStrings.yml


stages: 

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: DeployConfigDataToSystemTest
    displayName: Deploy Config Data To System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToSystemTest
      environment: PfPSystemTest
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      
      strategy:
        runOnce:
          deploy:
      

            steps:
              - checkout: self
              
              - task: MSCRMToolInstaller@12
                inputs:
                  nugetFeed: 'official'
                  psFeed: 'official'   

              - template : config-data-template.yml
                parameters :
                  connectionString: $(pfpsystemtest.connection.string)
              
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------


#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: DeployConfigDataToUAT
    displayName: Deploy Config Data To UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToTisskiUAT
      environment: PfPUAT
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      strategy:
        runOnce:
          deploy:
      

            steps:
              - checkout: self
              
              - task: MSCRMToolInstaller@12
                inputs:
                  nugetFeed: 'official'
                  psFeed: 'official'   

              - task: MSCRMGetConfigurationRecord@12
                inputs:
                  crmConnectionString: $(Tisskipfpuat.connection.string)
                  entityName: 'cp_configdatahistory'
                  lookupFieldName: 'cp_name'
                  valueFieldName: 'cp_value'
                  lookupValue: 'CurrentVersionRPRP'
                  existsVariableName: 'configExists'
                  valueVariableName: 'currentConfigVersion'
              
              - powershell: |
                        $value = Get-Content  -Path $(Build.SourcesDirectory)/ConfigData/CumbriaRPRPVersionDate.txt 
                        Write-Host "##vso[task.setvariable variable=newConfigVersion]$value"

              - task: MSCRMImportCMData@12
                displayName: Import Configuration Data
                inputs:
                  crmConnectionString: $(Tisskipfpuat.connection.string)
                  dataFile: $(Build.SourcesDirectory)/ConfigData/CumbriaRPRP.zip
                condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

              
              - task: MSCRMUpdateConfigurationRecords@12
                inputs:
                  crmConnectionString: '$(Tisskipfpuat.connection.string)'
                  entityName: 'cp_configdatahistory'
                  lookupFieldName: 'cp_name'
                  valueFieldName: 'cp_value'
                  configurationRecordsJson: '[[''CurrentVersionRPRP'',''$(newConfigVersion)'']]'
                condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToCumbriaUAT
      environment: PfPUAT
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      strategy:
        runOnce:
          deploy:
      

            steps:
              - checkout: self
              
              - task: MSCRMToolInstaller@12
                inputs:
                  nugetFeed: 'official'
                  psFeed: 'official'   

              - task: MSCRMGetConfigurationRecord@12
                inputs:
                  crmConnectionString: $(Cumbriapfpuat.connection.string)
                  entityName: 'cp_configdatahistory'
                  lookupFieldName: 'cp_name'
                  valueFieldName: 'cp_value'
                  lookupValue: 'CurrentVersionRPRP'
                  existsVariableName: 'configExists'
                  valueVariableName: 'currentConfigVersion'
              
              - powershell: |
                        $value = Get-Content  -Path $(Build.SourcesDirectory)/ConfigData/CumbriaRPRPVersionDate.txt 
                        Write-Host "##vso[task.setvariable variable=newConfigVersion]$value"

              - task: MSCRMImportCMData@12
                displayName: Import Configuration Data
                inputs:
                  crmConnectionString: $(Cumbriapfpuat.connection.string)
                  dataFile: $(Build.SourcesDirectory)/ConfigData/CumbriaRPRP.zip
                condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

              
              - task: MSCRMUpdateConfigurationRecords@12
                inputs:
                  crmConnectionString: '$(Cumbriapfpuat.connection.string)'
                  entityName: 'cp_configdatahistory'
                  lookupFieldName: 'cp_name'
                  valueFieldName: 'cp_value'
                  configurationRecordsJson: '[[''CurrentVersionRPRP'',''$(newConfigVersion)'']]'
                condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------



