trigger: none


pool:
  name: MOD Pool


variables:
- template: connectionStrings.yml


stages: 

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: DeployConfigDataToSystemTest
    displayName: Deploy Config Data To System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: 
      displayName: Deploy Config Data
      
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  

      steps:

      - task: MSCRMToolInstaller@12
        inputs:
          nugetFeed: 'official'
          psFeed: 'official'   

      - task: MSCRMGetConfigurationRecord@12
        inputs:
          crmConnectionString: $(pfpsystemtest.connection.string)
          entityName: 'cp_configdatahistory'
          lookupFieldName: 'cp_name'
          valueFieldName: 'cp_value'
          lookupValue: 'CurrentVersionRPRP'
          existsVariableName: 'configExists'
          valueVariableName: 'currentConfigVersion'
      
      - powershell: |
                $value = Get-Content  -Path $(pipeline.workspace)/CumbriaBuild-Managed-SystemTest/DataMigration/${{parameters.customer}}VersionDate.txt 
                Write-Host "##vso[task.setvariable variable=newConfigVersion]$value"

      - task: MSCRMImportCMData@12
        displayName: Import Configuration Data
        inputs:
          crmConnectionString: $(pfpsystemtest.connection.string)
          dataFile: $(pipeline.workspace)/CumbriaBuild-Managed-SystemTest/DataMigration/${{parameters.customer}}.zip
        condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

      
      - task: MSCRMUpdateConfigurationRecords@12
        inputs:
          crmConnectionString: '$(pfpsystemtest.connection.string)'
          entityName: 'cp_configdatahistory'
          lookupFieldName: 'cp_name'
          valueFieldName: 'cp_value'
          configurationRecordsJson: '[[''CurrentVersionRPRP'',''$(newConfigVersion)'']]'
        condition: ne (variables.newConfigVersion,variables.currentConfigVersion)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------




