trigger: none


pool:
  vmImage: windows-latest

stages:

  - stage: BuildAPI
    displayName: BuildAPI
    jobs:
    - job: BuildAPI
      steps:
        - template: buildAPI.yml
          parameters:
            configuration: Release


  