trigger:
  batch: true
  branches: 
      include:
      - master
  paths:
    include:
    - MiddleTier/*


pool:
  vmImage: windows-latest

stages:

  - stage: BuildAPI
    displayName: BuildAPI
    jobs:
    - job: BuildAPI
      steps:
        - template: buildAPI.yml
          parameters:
            configuration: Release

  - stage: DeployAPIToDev
    displayName: Deploy API to Dev
    jobs:
    - deployment: DeployAPIToPfPDev
      environment: PfPDevAzure
      displayName: Deploy API
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployAPI.yml
                parameters:
                  serviceConnectionName: PfPDev-ab46c5b7b4fa


  - stage: DeployAPIToTest
    displayName: Deploy API to SysTest
    jobs:
    - deployment: DeployAPIToPfPSysTest
      environment: PfPSysTestAzure
      displayName: Deploy API
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployAPI.yml
                parameters:
                  serviceConnectionName: PfPSysTest-ec70


  - stage: DeployAPIToUAT
    displayName: Deploy API to UAT
    jobs:
    - deployment: DeployAPIToPfPUAT
      environment: PfPUATAzure
      displayName: Deploy API
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployAPI.yml
                parameters:
                  serviceConnectionName: PfPUAT-8975

  