parameters:
- name: WebResourcesSolutionName
  type: string
  default: WebResources
- name: OptionSetsSolutionName
  type: string
  default: OptionSets
- name: EntitiesSolutionName
  type: string
  default: Entities
- name: SecurityRolesSolutionName
  type: string
  default: SecurityRoles
- name: ProcessesSolutionName
  type: string
  default: Processes
- name: PluginsSolutionName
  type: string
  default: Plugins
- name: PluginStepsSolutionName
  type: string
  default: PluginSteps
- name: ModelDrivenAppsSolutionName
  type: string
  default: ModelDrivenApps
- name: FlowsVehicleSolutionName
  type: string
  default: FlowsVehicle
- name: FlowsPNCSolutionName
  type: string
  default: FlowsPNC

- name: Release
  values:
  - CP
  - RP
#- name: solutionName
#  type: string
#  default: 
#  values:
#  - WebResources
#  - OptionSets
#  - Entities
#  - SecurityRoles
#  - Processes
#  - Plugins
#  - PluginSteps
#  - Dashboards
#  - ModelDrivenApps
  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: ${{parameters.release}}
- template: connectionStrings.yml


name: $(Build.DefinitionName) - $(Build.BuildId) 

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet '

      - task: MSCRMToolInstaller@9
        displayName: 'MSCRM Tool Installer'

      - task: DeleteFiles@1
        displayName: 'Delete files from $(build.binariesdirectory)'
        inputs:
          SourceFolder: '$(build.binariesdirectory)'
          Contents: '**'

      - ${{ each parameter in parameters }}:
        - ${{ if contains(parameter.Key, 'SolutionName') }}:
          - template: assembleAndCheck.yml
            parameters:
              solutionName: ${{parameter.Value}}
              folderNames: CanvasApps,Other
              managed: Managed
              solutionprefix: $(solution.prefix)
              minorversion: $(minor.version)
              releaseversion: $(release.version)


      - publish: '$(build.binariesdirectory)/SystemTest'
        artifact: CumbriaBuild-Managed-RPRP

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToTisskiPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Release to Tisski PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToTisskiPfPSystemTest
      environment: PfPSystemTest
      displayName: Release To Tisski PfP SystemTest
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'

            - template: get-solution-filenames.yml
              parameters:
                pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: deployBaseSolution.yml
                  parameters:
                    minorversion : $(minor.version)
                    releaseversion : $(release.version)
                    solutionprefix : $(solution.prefix)
                    solutionName: ${{parameter.Value}}
                    connectionString: $(pfpsystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToSystemTest
      dependsOn: ReleaseToTisskiPfPSystemTest
      environment: PfPSystemTest
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      
      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(pfpsystemtest.connection.string)
                  suffix: $(solution.prefix)

      
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaUAT
    dependsOn: ReleaseToTisskiPfPSystemTest
    displayName: Release to Cumbria UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaUAT
      environment: CumbriaUAT
      displayName: Release To Cumbria UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: deployBaseSolution.yml
                  parameters:
                    minorversion : $(minor.version)
                    releaseversion : $(release.version)
                    solutionprefix : $(solution.prefix)
                    solutionName: ${{parameter.Value}}
                    connectionString: $(Cumbriapfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToCumbriaUAT
      dependsOn: ReleaseToCumbriaUAT
      environment: CumbriaUAT
      displayName: Deploy Config Data To Cumbria UAT
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  

      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(Cumbriapfpuat.connection.string)
                  suffix: $(solution.prefix)
              
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToTisskiPfPUAT
    dependsOn: ReleaseToTisskiPfPSystemTest
    displayName: Release to Tisski PfP UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToTisskiPfPUAT
      environment: PfPUAT
      displayName: Release To Tisski PfP UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: deployBaseSolution.yml
                  parameters:
                    minorversion : $(minor.version)
                    releaseversion : $(release.version)
                    solutionprefix : $(solution.prefix)
                    solutionName: ${{parameter.Value}}
                    connectionString: $(Tisskipfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToTisskiPfPUAT
      dependsOn: ReleaseToTisskiPfPUAT
      environment: PfPUAT
      displayName: Deploy Config Data To Tisski PfP UAT
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  

      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(Tisskipfpuat.connection.string)
                  suffix: $(solution.prefix)
              
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
