parameters:
- name: WebResourcesSolutionName
  type: string
  default: WebResources
- name: OptionSetsSolutionName
  type: string
  default: OptionSets
- name: EntitiesSolutionName
  type: string
  default: Entities
- name: SecurityRolesSolutionName
  type: string
  default: SecurityRoles
- name: ProcessesSolutionName
  type: string
  default: Processes
- name: PluginsSolutionName
  type: string
  default: Plugins
- name: PluginStepsSolutionName
  type: string
  default: PluginSteps
- name: ModelDrivenAppsSolutionName
  type: string
  default: ModelDrivenApps
- name: FlowsVehicleSolutionName
  type: string
  default: FlowsVehicle
- name: FlowsCovidSolutionName
  type: string
  default: FlowsCovid
- name: FlowsStatementSolutionName
  type: string
  default: FlowsStatement
- name: FlowsItsYourChoiceSolutionName
  type: string
  default: FlowsItsYourChoice
- name: FlowsUseOfForceSolutionName
  type: string
  default: FlowsUseOfForce
- name: FlowsPDFSolutionName*
  type: string
  default: FlowsPDF

- name: CumbriaCustomerName
  type: string
  default: Cumbria

- name: DurhamCustomerName
  type: string
  default: Durham

- name: SystemTestEnvironmentName
  type: string
  default: SystemTest

- name: UATEnvironmentName
  type: string
  default: UAT

- name: LiveEnvironmentName
  type: string
  default: Live


- name: Release
  values:
  - CP
  - RP
#- name: solutionName
#  type: string
#  default: 
#  values:
#  - WebResources
#  - OptionSets
#  - Entities
#  - SecurityRoles
#  - Processes
#  - Plugins
#  - PluginSteps
#  - Dashboards
#  - ModelDrivenApps
  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: ${{parameters.release}}
- template: connectionStrings.yml


name: $(Build.DefinitionName) - $(Build.BuildId) 

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: RewriteFiles
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: BuildRewriteTools
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 5.0.100'
        inputs:
          packageType: 'sdk'
          version: '5.0.100'
          includePreviewVersions: true
                
      - task: DotNetCoreCLI@2
        displayName: Build Flow Rewriter Tool
        inputs:
          command: 'build'
          projects: 'PipelineTools/FlowRewriter/FlowRewriter.csproj'
            
      - task: CmdLine@2
        displayName: Run Flow Rewriter Tool
        inputs:
          workingDirectory: $(build.sourcesdirectory)/PipelineTools/FlowRewriter/bin/Debug/net5.0
          script: |
            $(build.sourcesdirectory)/PipelineTools/FlowRewriter/bin/Debug/net5.0/FlowRewriter.exe
      - task: PublishBuildArtifacts@1
        displayName: Publish Rewritten Flows
        inputs:
          PathtoPublish: '$(build.sourcesdirectory)/PipelineTools/FlowRewriter/RewrittenFlows'
          ArtifactName: 'RewrittenFlows'
          publishLocation: 'Container'
      


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet '

      - task: MSCRMToolInstaller@9
        displayName: 'MSCRM Tool Installer'

      - task: DeleteFiles@1
        displayName: 'Delete files from $(build.binariesdirectory)'
        inputs:
          SourceFolder: '$(build.binariesdirectory)'
          Contents: '**'
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'RewrittenFlows'
          path: $(Build.SourcesDirectory)/RewrittenFlows

      - ${{ each parameter in parameters }}:
        - ${{ if contains(parameter.Key, 'SolutionName') }}:
          - ${{ each parameter2 in parameters }}:
            - ${{ if contains(parameter2.Key, 'CustomerName') }}:
              - ${{ each parameter3 in parameters }}:
                - ${{ if contains(parameter3.Key, 'EnvironmentName') }}:
                  - template: assembleAndCheck.yml
                    parameters:
                      environmentName: ${{parameter3.Value}}
                      customerName: ${{parameter2.Value}}
                      solutionName: ${{parameter.Value}}
                      folderNames: CanvasApps,Other
                      managed: Managed
                      solutionprefix: $(solution.prefix)
                      minorversion: $(minor.version)
                      releaseversion: $(release.version)


      - publish: '$(build.binariesdirectory)/SystemTest'
        artifact: CumbriaBuild-Managed-RPRP

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToTisskiPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Release to Tisski PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToTisskiPfPSystemTest
      environment: PfPSystemTest
      displayName: Release To Tisski PfP SystemTest
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'

            - template: get-solution-filenames.yml
              parameters:
                pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: install-managed-solution.yml
                  parameters:
                    SolutionFileName : $(${{parameter.Value}}SolutionFileName)
                    pipelineworkspace: $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                    connectionString: $(pfpsystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToSystemTest
      dependsOn: ReleaseToTisskiPfPSystemTest
      environment: PfPSystemTest
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      
      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(pfpsystemtest.connection.string)
                  suffix: $(solution.prefix)
                  customer: Cumbria

      
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaSystemTest
    dependsOn: AssembleRelease
    displayName: Release to Cumbria System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaSystemTest
      environment: CumbriaSystemTest
      displayName: Release To Cumbria SystemTest
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'

            - template: get-solution-filenames.yml
              parameters:
                pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: install-managed-solution.yml
                  parameters:
                    SolutionFileName : $(${{parameter.Value}}SolutionFileName)
                    pipelineworkspace: $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                    connectionString: $(cumbriasystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToCumbriaSystemTest
      dependsOn: ReleaseToCumbriaSystemTest
      environment: CumbriaSystemTest
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      
      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(cumbriasystemtest.connection.string)
                  suffix: $(solution.prefix)
                  customer: Cumbria

      
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToDurhamSystemTest
    dependsOn: AssembleRelease
    displayName: Release to Durham System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToDurhamSystemTest
      environment: DurhamSystemTest
      displayName: Release To Durham SystemTest
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'

            - template: get-solution-filenames.yml
              parameters:
                pipelineworkspace : $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: install-managed-solution.yml
                  parameters:
                    SolutionFileName : $(${{parameter.Value}}SolutionFileName)
                    pipelineworkspace: $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                    connectionString: $(durhamsystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToDurhamSystemTest
      dependsOn: ReleaseToDurhamSystemTest
      environment: DurhamSystemTest
      displayName: Deploy Config Data
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  
      
      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(durhamsystemtest.connection.string)
                  suffix: $(solution.prefix)
                  customer: Durham

      
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaUAT
    dependsOn: ReleaseToCumbriaSystemTest
    displayName: Release to Cumbria UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaUAT
      environment: CumbriaUAT
      displayName: Release To Cumbria UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: install-managed-solution.yml
                  parameters:
                    SolutionFileName : $(${{parameter.Value}}SolutionFileName)
                    pipelineworkspace: $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                    connectionString: $(Cumbriapfpuat.connection.string)



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToCumbriaUAT
      dependsOn: ReleaseToCumbriaUAT
      environment: CumbriaUAT
      displayName: Deploy Config Data To Cumbria UAT
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  

      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(Cumbriapfpuat.connection.string)
                  suffix: $(solution.prefix)
                  customer: Cumbria
              
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToTisskiPfPUAT
    dependsOn: ReleaseToTisskiPfPSystemTest
    displayName: Release to Tisski PfP UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToTisskiPfPUAT
      environment: PfPUAT
      displayName: Release To Tisski PfP UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            
            - checkout: none
            - task: MSCRMToolInstaller@9
              displayName: 'MSCRM Tool Installer'
            
            - ${{ each parameter in parameters }}:
              - ${{ if contains(parameter.Key, 'SolutionName') }}:
                - template: install-managed-solution.yml
                  parameters:
                    SolutionFileName : $(${{parameter.Value}}SolutionFileName)
                    pipelineworkspace: $(pipeline.workspace)\CumbriaBuild-Managed-RPRP
                    connectionString: $(Tisskipfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: DeployConfigDataToTisskiPfPUAT
      dependsOn: ReleaseToTisskiPfPUAT
      environment: PfPUAT
      displayName: Deploy Config Data To Tisski PfP UAT
     # workspace:
     #   clean: all 
      variables:
      - name: configExists
      - name: currentConfigVersion  
      - name: newConfigVersion  

      strategy:
        runOnce:
          deploy:
            steps:
              - template : config-data-template.yml
                parameters :
                  connectionString: $(Tisskipfpuat.connection.string)
                  suffix: $(solution.prefix)
                  customer: Cumbria           
              
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
