#parameters:
#- name: prefix
#  type: string
#  default: 
#  values:
#  - CP
#  - RP
#- name: solutionName
#  type: string
#  default: 
#  values:
#  - WebResources
#  - OptionSets
#  - Entities
#  - SecurityRoles
#  - Processes
#  - Plugins
#  - PluginSteps
#  - Dashboards
#  - ModelDrivenApps
  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: "RP"
- template: connectionStrings.yml

name: $(Build.DefinitionName) - $(Build.BuildId) 

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet '

      - task: MSCRMToolInstaller@9
        displayName: 'MSCRM Tool Installer'

      - template: assembleAndCheck.yml
        parameters:
          solutionName: WebResources
          folderNames: CanvasApps,Other
          managed: Managed
          solutionprefix: $(solution.prefix)
          minorversion: $(minor.version)
          releaseversion: $(release.version)

      - template: assembleAndCheck.yml
        parameters:
          solutionName: OptionSets
          folderNames: CanvasApps,Other
          managed: Managed
          solutionprefix: $(solution.prefix)
          minorversion: $(minor.version)
          releaseversion: $(release.version)

      - template: assembleAndCheck.yml
        parameters:
          solutionName: Entities
          folderNames: CanvasApps,Other
          managed: Managed
          solutionprefix: $(solution.prefix)
          minorversion: $(minor.version)
          releaseversion: $(release.version)

      - publish: '$(build.binariesdirectory)/SystemTest'
        artifact: CumbriaBuild-Managed-RPRP

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
