parameters:
- name: canvasApp
  type: string
  default: PocketNotebook
  values:
  - PocketNotebookAzure
  - SuddenDeathAzure
  - SuddenDeath
  - PocketNotebook
  - Vehicle*

- name: CumbriaCustomerName
  type: string
  default: Cumbria

- name: DurhamCustomerName
  type: string
  default: Durham

- name: SystemTestEnvironmentName
  type: string
  default: SystemTest

- name: UATEnvironmentName
  type: string
  default: UAT

- name: LiveEnvironmentName
  type: string
  default: Live

  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: CP
- template: connectionStrings.yml



stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: RewriteFiles
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: BuildRewriteTools
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 5.0.100'
        inputs:
          packageType: 'sdk'
          version: '5.0.100'
          includePreviewVersions: true
                
      - task: DotNetCoreCLI@2
        displayName: Build App Rewriter Tool
        inputs:
          command: 'build'
          projects: 'PipelineTools/CanvasAppRewriter/CanvasAppRewriter.csproj'
            
      - task: CmdLine@2
        displayName: Run CanvasApp Rewriter Tool
        inputs:
          workingDirectory: $(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/bin/Debug/net5.0
          script: |
            $(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/bin/Debug/net5.0/CanvasAppRewriter.exe
      - task: PublishBuildArtifacts@1
        displayName: Publish Rewritten CanvasApps
        inputs:
          PathtoPublish: '$(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/RewrittenCanvasApps'
          ArtifactName: 'RewrittenCanvasApps'
          publishLocation: 'Container'
      


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'RewrittenCanvasApps'
          path: $(Build.SourcesDirectory)/RewrittenCanvasApps

      - ${{ if endsWith(parameters.canvasApp,'*') }}:
        - ${{ each parameter2 in parameters }}:
          - ${{ if contains(parameter2.Key, 'CustomerName') }}:
            - ${{ each parameter3 in parameters }}:
              - ${{ if contains(parameter3.Key, 'EnvironmentName') }}:

                - template: assembleReleaseForApp.yml
                  parameters:
                    managed: Managed
                    minorversion : $(minor.version)
                    releaseversion : $(release.version)
                    solutionprefix : $(solution.prefix)
                    appFolderName : CanvasApps${{replace(parameters.canvasApp,'*','')}}
                    environmentName: ${{parameter3.Value}}
                    customerName: ${{parameter2.Value}}

      - ${{ if not(endsWith(parameters.canvasApp,'*')) }}:
        - template: assembleReleaseForApp.yml
          parameters:
            managed: Managed
            minorversion : $(minor.version)
            releaseversion : $(release.version)
            solutionprefix : $(solution.prefix)
            appFolderName : CanvasApps${{parameters.canvasApp}}
            environmentName: Base
            customerName: Base

      - publish: '$(build.binariesdirectory)'
        artifact: PowerAppsForPolicingCanvasApp

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPSystemTest
      environment: PfPSystemTest
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(pfpsystemtest.connection.string)
                customername: Cumbria
                environmentname: SystemTest


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy Cumbria System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaSystemTest
      environment: CumbriaSystemTest
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(cumbriasystemtest.connection.string)
                customername: Cumbria
                environmentname: SystemTest


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaUAT
    dependsOn: ReleaseToCumbriaSystemTest
    displayName: Deploy Cumbria UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaUAT
      environment: CumbriaUAT
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(cumbriauat.connection.string)
                customername: Cumbria
                environmentname: UAT


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaLive
    dependsOn: ReleaseToCumbriaUAT
    displayName: Deploy Cumbria Live
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaLive
      environment: CumbriaLive
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(cumbrialive.connection.string)
                customername: Cumbria
                environmentname: Live


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToDurhamSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy Durham System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToDurhamSystemTest
      environment: DurhamSystemTest
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(durhamsystemtest.connection.string)
                customername: Durham
                environmentname: SystemTest


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToUAT
    dependsOn: ReleaseToPfPSystemTest
    displayName: Deploy to PfP UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPUAT
      environment: PfPUAT
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(Tisskipfpuat.connection.string)
                customername: Cumbria
                environmentname: UAT


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------


