parameters:
- name: prefix
  type: string
  default: 
  values:
  - CP
  - RP
- name: solutionName
  type: string
  default: 
  values:
  - WebResources
  - OptionSets
  - Entities
  - SecurityRoles
  - Processes
  - Plugins
  - PluginSteps
  - Dashboards
  - ModelDrivenApps
  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: ${{parameters.prefix}}
- template: connectionStrings.yml

name: $(Build.DefinitionName) - $(Build.BuildId) - ${{parameters.solutionName}}

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - template: assembleReleaseForBaseSolution.yml
        parameters:
          managed: Managed
          minorversion : $(minor.version)
          releaseversion : $(release.version)
          solutionprefix : $(solution.prefix)
          appFolderName : ${{parameters.solutionName}}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPSystemTest
      environment: PfPSysTestAzure
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployBaseSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                solutionName: ${{parameters.solutionName}}
                connectionString: $(pfpsystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToTisskiUAT
    dependsOn: ReleaseToPfPSystemTest
    displayName: Release to Tisski UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToTisskiUAT
      environment: PfPUATAzure
      displayName: Release to Tisski UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployBaseSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                solutionName: ${{parameters.solutionName}}
                connectionString: $(Tisskipfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------


#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToCumbriaUAT
    dependsOn: ReleaseToPfPSystemTest
    displayName: Release to Cumbria UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToCumbriaUAT
      environment: PfPUATAzure
      displayName: Release to Cumbria UAT
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployBaseSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                solutionName: ${{parameters.solutionName}}
                connectionString: $(Cumbriapfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

