parameters:
- name: canvasApp
  type: string
  default: PocketNotebook
  values:
  - PocketNotebookAzure
  - SuddenDeathAzure
  - PocketNotebook
  - Vehicle

- name: customer
  type: string
  default: Cumbria
  values:
  - Cumbria
  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: CP
- template: connectionStrings.yml

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - template: assembleReleaseForApp.yml
        parameters:
          managed: Managed
          minorversion : $(minor.version)
          releaseversion : $(release.version)
          solutionprefix : $(solution.prefix)
          appFolderName : CanvasApps${{parameters.canvasApp}}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPSystemTest
      environment: PfPSystemTest
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(pfpsystemtest.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToUAT
    dependsOn: ReleaseToPfPSystemTest
    displayName: Deploy to PfP UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPUAT
      environment: PfPUAT
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(Tisskipfpuat.connection.string)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------


