parameters:
- name: canvasApp
  type: string
  default: PocketNotebook
  values:
  - PocketNotebookAzure
  - SuddenDeathAzure
  - PocketNotebook
  - Vehicle

  
trigger: none

pool:
  name: MOD Pool

variables:
- name: minor.version
  value: 0
- name: release.version
  value: 0 
- name: solution.prefix
  value: CP
- template: connectionStrings.yml

stages: 
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: RewriteFiles
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: BuildRewriteTools
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 5.0.100'
        inputs:
          packageType: 'sdk'
          version: '5.0.100'
          includePreviewVersions: true
                
      - task: DotNetCoreCLI@2
        displayName: Build App Rewriter Tool
        inputs:
          command: 'build'
          projects: 'PipelineTools/CanvasAppRewriter/CanvasAppRewriter.csproj'
            
      - task: CmdLine@2
        displayName: Run CanvasApp Rewriter Tool
        inputs:
          workingDirectory: $(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/bin/Debug/net5.0
          script: |
            $(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/bin/Debug/net5.0/CanvasAppRewriter.exe
      - task: PublishBuildArtifacts@1
        displayName: Publish Rewritten CanvasApps
        inputs:
          PathtoPublish: '$(build.sourcesdirectory)/PipelineTools/CanvasAppRewriter/RewrittenCanvasApp'
          ArtifactName: 'CanvasApp'
          publishLocation: 'Container'
      


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------
  - stage: AssembleRelease
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - job: Assemble
      steps:
      - template: assembleReleaseForApp.yml
        parameters:
          managed: Managed
          minorversion : $(minor.version)
          releaseversion : $(release.version)
          solutionprefix : $(solution.prefix)
          appFolderName : CanvasApps${{parameters.canvasApp}}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#----------------------------------End Stage-------------------------------------------------------------------
#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToPfPSystemTest
    dependsOn: AssembleRelease
    displayName: Deploy PfP System Test
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPSystemTest
      environment: PfPSystemTest
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: 'RewrittenCanvasApps'
                path: $(Build.SourcesDirectory)/RewrittenCanvasApps

            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(pfpsystemtest.connection.string)
                customername: Cumbria
                environmentname: SystemTest


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------

#----------------------------------Start Stage-------------------------------------------------------------------

  - stage: ReleaseToUAT
    dependsOn: ReleaseToPfPSystemTest
    displayName: Deploy to PfP UAT
    jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - deployment: ReleaseToPfPUAT
      environment: PfPUAT
      displayName: Deploy Solutions
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            
            steps:
            - template: deployCanvasAppSolution.yml
              parameters:
                minorversion : $(minor.version)
                releaseversion : $(release.version)
                solutionprefix : $(solution.prefix)
                canvasApp: ${{parameters.canvasApp}}
                connectionString: $(Tisskipfpuat.connection.string)
                customername: Cumbria
                environmentname: UAT


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Job~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#----------------------------------End Stage-------------------------------------------------------------------


