trigger: none


pool:
  vmImage: windows-latest

stages:
  - stage: DeployQueueListenersToDev
    displayName: Deploy Queue Listeners to Dev
    jobs:
    - job : BuildAndDeploy
      steps:
        - template: buildAndDeployQueueListeners.yml
          parameters:
            serviceConnectionName: PfPDev-ab46c5b7b4fa
            configuration: Release
            appName: PfPDev-ab46c5b7b4faQueueListeners

  - stage: DeployQueueListenersToSysTest
    displayName: Deploy Queue Listeners to SysTest
    jobs:
    - job : BuildAndDeploy
      steps:
        - template: buildAndDeployQueueListeners.yml
          parameters:
            serviceConnectionName: PfPSysTest-ec70
            configuration: Release
            appName: PfPSysTest-ec70QueueListeners

  - stage: DeployQueueListenersToUAT
    displayName: Deploy Queue Listeners to UAT
    jobs:
    - job : BuildAndDeploy
      steps:
        - template: buildAndDeployQueueListeners.yml
          parameters:
            serviceConnectionName: PfPUAT-e4a7
            configuration: Release
            appName: PfPUAT-e4a7QueueListeners
