trigger:
  batch: true
  branches: 
      include:
      - master
  paths:
    include:
    - MiddleTier


pool:
  vmImage: windows-latest

stages:

  - stage: BuildQueueListeners
    displayName: BuildQueueListeners
    jobs:
    - job: BuildQueueListeners
      steps:
        - template: buildQueueListeners.yml
          parameters:
            configuration: Release


  - stage: DeployQueueListenersToDev
    displayName: Deploy Queue Listeners to Dev
    jobs:
    - deployment: ReleaseToPfPDev
      environment: PfPDevAzure
      displayName: Deploy Queue Listeners
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployQueueListeners.yml
                parameters:
                  serviceConnectionName: PfPDev-ab46c5b7b4fa

  - stage: DeployQueueListenersToSysTest
    displayName: Deploy Queue Listeners to SysTest
    jobs:
    - deployment: ReleaseToPfPSysTest
      environment: PfPSysTestAzure
      displayName: Deploy Queue Listeners
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployQueueListeners.yml
                parameters:
                  serviceConnectionName: PfPSysTest-ec70

  - stage: DeployQueueListenersToUAT
    displayName: Deploy Queue Listeners to UAT
    jobs:
    - deployment: ReleaseToPfPUAT
      environment: PfPUATAzure
      displayName: Deploy Queue Listeners
      workspace:
        clean: all 
      strategy:
        runOnce:
          deploy:
            steps:
              - template: deployQueueListeners.yml
                parameters:
                  serviceConnectionName: PfPUAT-8975
