trigger: none

parameters:
- name: environmentConnection
  displayName: Azure Environment Connection
  type: string
  values:
  - CumbriaDevResourceGroupConnection
  - CumbriaSystemTestResourceGroupConnection
  - PowerAppsForPolicingDevResourceGroupConnection

pool:
  vmImage: windows-latest

stages:
  - stage: DeployQueueListeners
    displayName: Deploy Queue Listeners to ${{environmentConnection}}
    jobs:
    - job : BuildAndDeploy
      steps:
        - template: buildAndDeployQueueListeners.yml
          parameters:
            serviceConnectionName: ${{environmentConnection}}
            configuration: Release
            appName: TisskiPolicingQueueListeners