trigger: none

parameters:
- name: environmentConnection
  displayName: Azure Environment Connection
  type: string
  default: 
  values:
  - CumbriaDev
  - CumbriaSystemTest
  - PowerAppsForPolicing

pool:
  vmImage: windows-latest

stages:
  - stage: DeployQueueListeners
    displayName: Deploy Queue Listeners to ${{parameters.environmentConnection}}
    jobs:
    - job : BuildAndDeploy
      steps:
        - template: buildAndDeployQueueListeners.yml
          parameters:
            serviceConnectionName: ${{parameters.environmentConnection}}ResourceGroupConnection
            configuration: Release
            appName: ${{parameters.environmentConnection}}QueueListeners